import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Header
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.ourTeam': 'Our Team',
    'nav.bankAccounts': 'Bank Accounts & Payments',
    'nav.invitations': 'Invitations',
    'nav.typesOfInvitation': 'Types Of Invitation',
    'nav.detailsAndCosts': 'Details & Costs',
    'nav.applyInvitation': 'Apply Invitation Letter',
    'nav.visas': 'Visas',
    'nav.availableVisas': 'Available Visas',
    'nav.visitingVisas': 'Visiting Visas',
    'nav.studyingVisas': 'Studying Visas',
    'nav.companyReg': 'Company Reg',
    'nav.allCompaniesReg': 'All Companies Reg',
    'nav.applyCompanyReg': 'Apply for Company Reg',
    'nav.immigration': 'Immigration',
    'nav.businessImmigration': 'Business Immigration',
    'nav.contact': 'Contact',
    'nav.bookAppointment': 'Book Appointment',

    // Footer
    'footer.getFreeAssessment': 'Get Free Assessment Today!',
    'footer.feelFreeToEnquire': 'Feel Free To Enquire About Any Questions You Got',
    'footer.fullName': 'Full Name',
    'footer.emailAddress': 'Email Address',
    'footer.yourMessage': 'Your Message',
    'footer.submitting': 'Submitting...',
    'footer.submit': 'Submit',
    'footer.contactInformation': 'Contact Information',
    'footer.quickLinks': 'Quick Links',
    'footer.ourServices': 'Our Services',
    'footer.contactInfo': 'Contact Info',
    'footer.allRightsReserved': 'All rights reserved.',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.aboutText': 'Our main focus is helping our clients move from their countries to EU with expert guidance and support.',
    'footer.successMessage': 'Assessment request sent successfully!',
    'footer.errorMessage': 'Oops! There was a problem submitting your request.',
    'form.success': 'Sent successfully!',
    'form.error': 'Oops! There was a problem.',
    'form.submitting': 'Sending...',
    'contact.heroTitle': 'Contact',
    'contact.heroBreadcrumb': 'Home / Contact',
    'contact.getInTouch': 'GET IN TOUCH',
    'contact.contactGlobestar': 'Contact GLOBESTAR',
    'contact.startConversation': 'Lets Start Conversation Today',
    'contact.howWeHelp': 'HOW WE HELP CLIENTS',
    'contact.contactInfoTitle': 'Contact Information',
    'contact.address': 'ADDRESS',
    'contact.phone': 'PHONE',
    'contact.email': 'EMAIL',
    'contact.workingHours': 'WORKING HOURS',
    'contact.monFri': 'Monday – Friday: 9:00 – 18:00',
    'contact.satSun': 'Saturday & Sunday: Closed',
    'contact.sendUsMessage': 'Send Us a Message',
    'contact.firstName': 'FIRST NAME *',
    'contact.firstNamePlaceholder': 'Your first name',
    'contact.emailAddress': 'EMAIL ADDRESS *',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.phoneNumber': 'PHONE NUMBER',
    'contact.phonePlaceholder': '+1 234 567 890',
    'contact.yourCountry': 'YOUR COUNTRY',
    'contact.countryPlaceholder': 'Your country of residence',
    'contact.serviceInterested': 'SERVICE INTERESTED IN',
    'contact.selectService': 'Select a Service',
    'contact.message': 'MESSAGE *',
    'contact.messagePlaceholder': 'Tell us how we can help you...',
    'contact.sendButton': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.successMessage': "Message sent successfully! We'll get back to you soon.",
    'contact.errorMessage': "Oops! There was a problem submitting your form",
    'apply.heroTitle': 'Apply Invitation Letter',
    'apply.heroBreadcrumb': 'Home / Invitations / Apply Invitation',
    'apply.applyHeading': 'Apply for an Invitation Letter',
    'apply.success': 'Application submitted successfully! We will process it within 3 business days.',
    'apply.error': 'Oops! There was a problem submitting your application.',

    // Our Team
    'team.heroTitle': 'Our Team',
    'team.heroBreadcrumb': 'Home / About / Our Team',
    'team.experiencedProfessionals': 'EXPERIENCED PROFESSIONALS',
    'team.meetOurExperts': 'Meet Our Experts',
    'team.aboutGlobestar': 'GLOBESTAR is a reputable and well-established company specializing in providing and arranging invitations for individuals seeking to visit European countries and the UK. Our team is dedicated to professional excellence.',
    'team.director': 'Director, GLOBESTAR',
    'team.managementOperations': 'Management & Operations',
    'team.legalConsultant': 'Legal Consultant',
    'team.visaImmigrationLaw': 'Visa & Immigration Law',
    'team.seniorConsultant': 'Senior Consultant',
    'team.businessImmigrationExpert': 'Business Immigration Expert',
    'team.deepExpertise': 'Deep expertise in facilitating invitations for Lithuania, Albania, Belarus, and the UK.',
    'team.combinedExperience': '20 Years of Combined Experience',
    'team.trustOurExpertise': 'Trust in our expertise to facilitate your journey and enhance your chances of a successful visa application.',
    'team.reputableCompany': 'Reputable and well-established company',
    'team.professionallyCrafted': 'Professionally crafted invitation letters',
    'team.alignRequirements': 'Align with specific visa application requirements',
    'team.dedicatedSupport': 'Dedicated support team',
    'team.visaSuccessRate': 'Visa Success Rate',
    'team.happyClients': 'Happy Clients',
    'team.destinations': 'Destinations',
    'team.clientSupport': 'Client Support',

    // Bank Account
    'bank.heroTitle': 'Bank Accounts',
    'bank.heroBreadcrumb': 'Home / About / Bank Accounts',
    'bank.paymentMethods': 'PAYMENT METHODS',
    'bank.officialAccounts': 'Our Official Bank Accounts',
    'bank.verifyAccount': 'Please use only our official accounts for any payments. Always verify the account name is GLOBESTAR.',
    'bank.copySuccess': 'Copied to clipboard',
    'bank.accountHolder': 'Account Holder',
    'bank.rib': 'RIB',
    'bank.iban': 'IBAN',
    'bank.swiftCode': 'SWIFT Code',
    'bank.accountName': 'Account Name',
    'bank.paypalEmail': 'PayPal Email',
    'bank.status': 'Status',
    'bank.verifiedBusiness': 'Verified Business',
    'bank.network': 'Network',
    'bank.asset': 'Asset',
    'bank.address': 'Address',
    'bank.securePolicy': 'Secure Payment Policy',
    'bank.quickSecure': 'Online payments are quick and secure.',
    'bank.immediateConfirmation': 'Immediate payment confirmation.',
    'bank.zeroFees': '0% Transaction fees for bank transfers.',
    'bank.whatsappSupport': 'WhatsApp support for payment assistance.',
    'bank.afterPayment': 'After making a payment, please send a screenshot of the transaction receipt to our official WhatsApp +34 624 13 21 71 or email us at globestarvisa@gmail.com for faster processing.',

    // Types of Invitation
    'invitation.heroTitle': 'Types of Invitation',
    'invitation.heroBreadcrumb': 'Home / Invitations / Types of Invitation',
    'invitation.visaDoc': 'VISA DOCUMENTATION',
    'invitation.typesLetters': 'Types of Invitation Letters',
    'invitation.choosingGlobestar': 'Choosing GLOBESTAR ensures a professionally crafted invitation letter that aligns with the specific visa application requirements of each respective country.',
    'invitation.visitTitle': 'Visit Visa Invitation',
    'invitation.visitDef': 'A document provided to individuals applying for visit visas, serving as a formal invitation from a host or sponsoring party in the destination country to stay with them.',
    'invitation.businessTitle': 'Business Visa Invitation',
    'invitation.businessDef': 'A formal invitation letter from a company for business visa purposes, usually for attending meetings, conferences, or professional engagements.',
    'invitation.familyTitle': 'Family Visa Invitation',
    'invitation.familyDef': 'A written letter from a host or company for family visitor visa purposes, required if you intend to visit your family members in the destination country.',
    'invitation.touristTitle': 'Tourist Visa Invitation',
    'invitation.touristDef': 'A written letter from a registered tourist company for tourist visa purposes, outlining the plan to explore and visit the country.',
    'invitation.privateTitle': 'Private Invitation',
    'invitation.privateDef': 'A written document from an individual in the host country to facilitate a tourist or private visit visa for an applicant.',
    'invitation.groupTitle': 'Group Invitation',
    'invitation.groupDef': 'A document issued by a company to facilitate tourist group visas for multiple individuals traveling together to the same destination.',
    'invitation.viewPricing': 'View Pricing & Apply',
    'invitation.whyNeed': 'Why do you need an Invitation Letter?',
    'invitation.officersConsider': 'Visa officers consider the invitation letter as a supporting document to assess the genuineness of the visit and the applicant’s intention to return to their home country. Trust in our expertise to facilitate your journey and enhance your chances of a successful visa application.',
    'country.lithuania': 'Lithuania',
    'country.albania': 'Albania',
    'country.uk': 'United Kingdom',
    'country.belarus': 'Belarus',
    'country.russia': 'Russia',
    'country.ukraine': 'Ukraine',
    'country.spain': 'Spain',
    'country.sweden': 'Sweden',
    'country.hungary': 'Hungary',
    'country.slovakia': 'Slovakia',
    'country.poland': 'Poland',

    // Details & Costs
    'costs.heroTitle': 'Details & Costs',
    'costs.heroBreadcrumb': 'Home / Invitations / Details & Costs',
    'costs.visaInvitationLetters': 'Visa Invitation Letters',
    'costs.businessInvitation': 'Business Invitation',
    'costs.applyNow': 'Apply Now',
    'costs.note': 'Note',
    'costs.search': 'Search',
    'costs.topServices': 'Our Top Services',
    'costs.anyQuestions': 'Any Questions?',
    'costs.callWhatsApp': 'Call / WhatsApp',
    'costs.emailUs': 'Email Us',
    'costs.invitationLetterHeading': 'Invitation Letter',
    'costs.para1': 'A visa invitation letter is a document provided to individuals applying for tourist, visit, business, or family visitor visas. It serves as a formal invitation from a host or sponsoring party in the destination country. While the invitation letter itself does not guarantee the issuance of a visa, it plays a crucial role in the visa application process by providing essential information about the purpose of the visit, the duration of stay, and the relationship between the applicant and the host.',
    'costs.para2': 'Visa officers consider the invitation letter as a supporting document to assess the genuineness of the visit and the applicant’s intention to return to their home country. Although not a guarantee of visa approval, having an invitation letter can significantly increase the chances of obtaining a visa.',
    'costs.para3': 'In the context of visiting Lithuania, Albania, Belarus, the UK, Russia, Ukraine, Spain, Sweden, and Hungary, securing a proper invitation letter is essential. GLOBESTAR is a reputable and well-established company specializing in providing and arranging invitations for individuals seeking to visit these countries.',
    'costs.para4': 'For those planning a visit to Lithuania, a "Lithuania visitor invitation letter" from GLOBESTAR can help communicate the purpose of the visit, the duration of stay, and the relationship between the visitor and the host in Lithuania.',
    'costs.applyHeading': 'Apply for an Invitation Letter',
    'costs.typesHeading': 'Types of Invitation Letter',
    'costs.globestarIsCompany': 'GLOBESTAR is a company that offers the following types of invitation letters:',
    'costs.paymentTermsHeading': 'Payment Terms',
    'costs.paymentPara1': 'We only accept documents with 100% advanced payment. Payment can be made through bank accounts and Visa/MasterCard credit cards. To view the bank account details, please visit the Services page and click on the Bank Account section. The payment slip will be attached to the Invitation Form.',
    'costs.paymentPara2': 'Please note that all payments are non-refundable. Once payment is confirmed, we will issue the invitation letter within 3 business days.',
    'costs.paymentPara3': 'The invitation letter will be sent to your email address. If you require a hard copy, an additional charge will apply. The specific charge depends on your country and may amount to $65.',
    'costs.howToGetHeading': 'How to get an Invitation Letter?',
    'costs.step1Title': 'Fill In The Invitation Form',
    'costs.step1Text': 'Please ensure that you fill out the online invitation form with the correct spellings according to the information in your passport',
    'costs.step2Title': 'Attach Passport & Proceed Payment',
    'costs.step2Text': "After filling out the form, please attach a scanned copy of your passport, then click the 'Submit' button and proceed with the payment.",
    'costs.step3Title': 'Get Ready To Receive your Invitation',
    'costs.step3Text': 'After receiving your application, passport copy, and payment confirmation, we will send your invitation letter to your email within 3 business days.',
    'costs.faqHeading': 'Frequently asked Questions',
    'costs.faq1Q': 'How long does it take for a visa invitation letter to be processed?',
    'costs.faq1A': 'Normally, we process visa invitation letters within three business days and send them via email. However, shipping may take approximately 3 to 10 days, depending on the destination country.',
    'costs.faq2Q': 'Do you also process visa applications for applicants?',
    'costs.faq2A': 'We provide visa support documentation (invitations) but the final application must be submitted by the applicant at the embassy or visa center.',
    'costs.faq3Q': 'How can we verify the authenticity and legality of the invitation?',
    'costs.faq3A': 'All our invitations are issued by legally registered companies and can be verified through the respective government migration portals where applicable.',
    'costs.noteMediation': 'The Letter of Mediation approved by Migration costs € 750.',
    'costs.notePerPerson': 'The cost of the Family Invitation letter is per person.',
    'costs.notePolice': 'The b. invitation letter is approved by the police/magistrate',
    'costs.noteTouristType': 'The family invitation letter will be of tourist type.',
    'country.estonia': 'Estonia',
    'country.serbia': 'Serbia',
    'country.kosovo': 'Kosovo',
    'country.cyprus': 'Cyprus',
    'country.luxembourg': 'Luxembourg',
    'country.netherlands': 'Netherlands',
    'country.germany': 'Germany',
    'country.czech': 'Czech Republic',
    'country.denmark': 'Denmark',
    'country.finland': 'Finland',
    'country.france': 'France',
    'country.iceland': 'Iceland',
    'country.norway': 'Norway',
    'country.portugal': 'Portugal',
    'country.ireland': 'Ireland',
    'invitation.visit': 'Visit Invitation',
    'invitation.business': 'Business Invitation',
    'invitation.family': 'Family Invitation',
    'invitation.tourist': 'Tourist Invitation',
    'invitation.perPerson': 'Per Person',
    'invitation.policeApproved': 'Police Approved Invitation',

    // Available Visas
    'visas.heroTitle': 'Available Visas',
    'visas.heroBreadcrumb': 'Home / Visas / Overview',
    'visas.servicesCategories': 'SERVICES CATEGORIES',
    'visas.exploreServices': 'Explore Our Visa Services',
    'visas.exploreDesc': 'Discover a wide range of visa and immigration services tailored to your needs. From work permits in Europe to study admissions in the UK.',
    'visas.visitingDesc': 'Travel permits for tourism and leisure. Includes E-visa options for countries such as Albania, Moldova, and Georgia.',
    'visas.studyingDesc': 'Educational permits for United Kingdom, Ireland and German universities. Includes support for language programs.',
    'visas.businessDesc': 'Dedicated services for entrepreneurs wishing to live and work in Lithuania, Estonia, and UK through business setup.',
    'visas.companyDesc': 'Fast and easy company incorporation in EU countries. Full legal assistance for your business establishment.',
    'visas.invitationDesc': 'Official company invitation letters required for visa applications. Business, Family, and Visit categories.',
    'visas.viewDetails': 'View Details',
    'visas.readyToStart': 'Ready to Start Your Application Journey?',
    'visas.expertsAvailable': 'Our experts are available 24/7 on WhatsApp to provide you with a free assessment of your eligibility.',

    // Visiting Visa
    'visiting.heroTitle': 'Visiting Visas & E-Visas',
    'visiting.heroBreadcrumb': 'Home / Visas / Visiting Visas',
    'visiting.servicesTitle': 'E-VISA SERVICES',
    'visiting.applyHeading': 'Apply for E-Visa',
    'visiting.para1': 'Travel visas allow the holder to enter a foreign country for tourism and leisure purposes only, and they typically have a specific duration of stay. However, it’s important to note that these visas generally do not grant the bearer the right to work or participate in any business activities while in the host country.',
    'visiting.para2': 'Embassy/ immigration grants three types of visas to applicants, 1. eTA (e-visa), 2. stamp visa & 3. sticker visa. We provide eTA visas for the many countries which are offering but these are for specific nationals.',
    'visiting.howToGetHeader': 'How To Get a Visa?',
    'visiting.step1Title': 'Fill In The Application Form',
    'visiting.step1Text': 'Please make sure to complete the online application form with the accurate spellings as per the information in your passport.',
    'visiting.step2Title': 'Attach Passport & Pay Fee',
    'visiting.step2Text': "After completing the form, please upload a scanned copy of your passport and proceed to payment by clicking 'Pay.' Finally, click the 'Submit' button.",
    'visiting.step3Title': 'Submit your Application',
    'visiting.step3Text': 'After receiving your application, passport copy, and payment confirmation, we will process your E-visa and notify you via email.',
    'visiting.typesHeading': 'Types of Visitor Visas',
    'visiting.generalTitle': 'General visitor visa',
    'visiting.generalText': 'This type of visitor visa is typically valid for a limited duration, ranging from a few days to a few months, depending on the country’s regulations. Upon expiration, you may need to either renew it or return to your home country.',
    'visiting.familyTitle': 'Family visitor visa',
    'visiting.familyText': 'Family visitor visas allow you to reside in a foreign country with your family. Depending on the specific country’s policies, you may be eligible to apply for renewal after a certain period of residence.',
    'visiting.businessTitle': 'Business visitor visa',
    'visiting.businessText': 'Business visitor visas enable you to live in a foreign country and establish your business there. After conducting business activities for a specific duration, you may be eligible to apply for temporary residence status.',
    'visiting.docReqHeading': 'Document Requirements',
    'visiting.reqPassport': 'Scanned all pages of current passport.',
    'visiting.reqID': 'Scanned ID/Residence card.',
    'visiting.reqPhoto': 'Digital picture with white background.',
    'visiting.reqPolice': 'Police Clearance Certificate (if required)',

    // Studying Visa
    'studying.heroTitle': 'Studying Visas & Admissions',
    'studying.heroBreadcrumb': 'Home / Visas / Studying Visas',
    'studying.servicesTitle': 'STUDENT ADMISSIONS',
    'studying.opportunitiesHeading': 'Study Abroad Opportunities',
    'studying.intro': 'GLOBESTAR provides admission services for studying in the United Kingdom & Ireland. We collaborate with a wide range of universities offering programs including ESL, ESOL, Foundation, Undergraduate, and Postgraduate courses across various fields.',
    'studying.ukTitle': 'UNITED KINGDOM',
    'studying.ukDesc': 'Study in the UK with top universities.',
    'studying.irelandTitle': 'IRELAND',
    'studying.irelandDesc': "Pursue your degree in Ireland's major cities.",
    'studying.germanyTitle': 'GERMANY',
    'studying.germanyDesc': 'Explore educational excellence in Germany.',
    'studying.languageProgHeading': 'Apply for Language Programs',
    'studying.languageIntro': 'To apply for language programs, there is no need to take the IELTS exam. There are no age restrictions, and study gaps are not considered as an issue. Tuition fees can be paid after obtaining the visa.',
    'studying.howLongHeading': 'How Long Does It Take?',
    'studying.studyVisaProcess': 'Study Visa: Usually processed in one to two months, depending on country and embassy.',
    'studying.admissionProcess': 'Admission: Processed in two to four weeks.',
    'studying.docReqHeading': 'Document Requirements',
    'studying.reqEdu': 'All educational documents (which having).',
    'studying.reqResume': 'Resume with your education & job details.',
    'studying.spain': 'Spain',
    'studying.italy': 'Italy',
    'studying.poland': 'Poland',
    'studying.france': 'France',
    'studying.spanish': 'Spanish Language',
    'studying.italian': 'Italian Language',
    'studying.polish': 'Polish Language',
    'studying.french': 'French Language',
    'studying.applyNow': 'Apply Now',

    // Company Registration
    'company.heroTitle': 'Companies Registration',
    'company.heroBreadcrumb': 'Home / Services / Company Registration',
    'company.supportHeading': 'COUNTRIES WE OFFER SUPPORT',
    'company.servicesHeading': 'Company Registration Services',
    'company.intro': 'Incorporating your business we make setting up your company fast and easy. We provide full legal assistance in the registration of your company.',
    'company.regLabel': 'Company Registration',
    'company.basicPackage': 'Basic Package',
    'company.needDetails': 'Need More Details?',
    'company.contactForDetails': 'For more details contact us via email & whatsapp',
    'company.getInTouch': 'Get In Touch',
    'company.disclaimer': 'GLOBESTAR is an approved Lithuanian company incorporated at the VALSTYBĖS ĮMONIŲ REGISTRŲ CENTRAS. Our registration number is 306016085',

    // Business Immigration
    'immigration.heroTitle': 'Business Immigration',
    'immigration.heroBreadcrumb': 'Home / Immigration / Business Immigration',
    'immigration.entrepreneurServices': 'ENTREPRENEUR SERVICES',
    'immigration.availableCountries': 'Business Immigration Available of the Following Countries',
    'immigration.startingAt': 'Starting at',
    'immigration.readMore': 'Read More',
    'immigration.trustedAssistance': 'Trusted Professional Assistance',
    'immigration.lithuaniaDesc': 'Our company deals exclusively with business immigration to Lithuania and has and reliable option to obtain a yearly multiple-entry business visa.',
    'immigration.estoniaDesc': 'Our company deals exclusively with business immigration to Estonia and has and reliable option to obtain a yearly multiple-entry business visa.',
    'immigration.albaniaDesc': 'GLOBESTAR provides a complete range of immigration services to foreign individuals and entrepreneurs, who wish to visit, live and work in Albania.',
    'immigration.belarusDesc': 'A Belarus Temporary Residence Permit is a document, issued to non-citizens who wish to have the opportunity to immigrate, live and work in Belarus.',
    'immigration.ukDesc': 'Everything you need to register and conduct a company in the UK. We provide full legal assistance in the registration of your company in the UK.',
    'immigration.irelandDesc': 'Everything you need to register and conduct a company in Ireland. We provide full legal assistance in the registration of your company in Ireland.',
    'immigration.visaProcessing': 'Visa Processing',
    'immigration.regIn': 'Registration in',
    'immigration.regLabel': 'Company Registration',
  },
  ar: {
    // Header
    'nav.home': 'الرئيسية',
    'nav.about': 'حول',
    'nav.ourTeam': 'فريقنا',
    'nav.bankAccounts': 'الحسابات البنكية والمدفوعات',
    'nav.invitations': 'الدعوات',
    'nav.typesOfInvitation': 'أنواع الدعوات',
    'nav.detailsAndCosts': 'التفاصيل والتكاليف',
    'nav.applyInvitation': 'طلب خطاب دعوة',
    'nav.visas': 'التأشيرات',
    'nav.availableVisas': 'التأشيرات المتاحة',
    'nav.visitingVisas': 'تأشيرات الزيارة',
    'nav.studyingVisas': 'تأشيرات الدراسة',
    'nav.companyReg': 'تسجيل الشركات',
    'nav.allCompaniesReg': 'جميع تسجيلات الشركات',
    'nav.applyCompanyReg': 'طلب تسجيل شركة',
    'nav.immigration': 'الهجرة',
    'nav.businessImmigration': 'الهجرة للأعمال',
    'nav.contact': 'اتصل بنا',
    'nav.bookAppointment': 'حجز موعد',

    // Footer
    'footer.getFreeAssessment': 'احصل على تقييم مجاني اليوم!',
    'footer.feelFreeToEnquire': 'لا تتردد في الاستفسار عن أي أسئلة لديك',
    'footer.fullName': 'الاسم الكامل',
    'footer.emailAddress': 'البريد الإلكتروني',
    'footer.yourMessage': 'رسالتك',
    'footer.submitting': 'جاري الإرسال...',
    'footer.submit': 'إرسال',
    'footer.contactInformation': 'معلومات الاتصال',
    'footer.quickLinks': 'روابط سريعة',
    'footer.ourServices': 'خدماتنا',
    'footer.contactInfo': 'معلومات الاتصال',
    'footer.allRightsReserved': 'جميع الحقوق محفوظة.',
    'footer.privacyPolicy': 'سياسة الخصوصية',
    'footer.termsOfService': 'شروط الخدمة',
    'footer.aboutText': 'ينصب تركيزنا الرئيسي على مساعدة عملائنا على الانتقال من بلدانهم إلى الاتحاد الأوروبي بتوجيه ودعم من الخبراء.',
    'footer.successMessage': 'تم الإرسال بنجاح',
    'footer.errorMessage': 'عذراً! حدثت مشكلة أثناء إرسال طلبك.',
    'form.success': 'تم الإرسال بنجاح!',
    'form.error': 'عذراً! حدثت مشكلة.',
    'form.submitting': 'جاري الإرسال...',
    'contact.heroTitle': 'اتصل بنا',
    'contact.heroBreadcrumb': 'الرئيسية / اتصل بنا',
    'contact.getInTouch': 'تواصل معنا',
    'contact.contactGlobestar': 'اتصل بـ غلوب ستار',
    'contact.startConversation': 'لنبدأ المحادثة اليوم',
    'contact.howWeHelp': 'كيف نساعد عملائنا',
    'contact.contactInfoTitle': 'معلومات الاتصال',
    'contact.address': 'العنوان',
    'contact.phone': 'الهاتف',
    'contact.email': 'البريد الإلكتروني',
    'contact.workingHours': 'ساعات العمل',
    'contact.monFri': 'الأثنين – الجمعة: 9:00 – 18:00',
    'contact.satSun': 'السبت والأحد: مغلق',
    'contact.sendUsMessage': 'أرسل لنا رسالة',
    'contact.firstName': 'الاسم الأول *',
    'contact.firstNamePlaceholder': 'اسمك الأول',
    'contact.emailAddress': 'عنوان البريد الإلكتروني *',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.phoneNumber': 'رقم الهاتف',
    'contact.phonePlaceholder': '+1 234 567 890',
    'contact.yourCountry': 'بلدك',
    'contact.countryPlaceholder': 'بلد إقامتك',
    'contact.serviceInterested': 'الخدمة المهتم بها',
    'contact.selectService': 'اختر خدمة',
    'contact.message': 'الرسالة *',
    'contact.messagePlaceholder': 'أخبرنا كيف يمكننا مساعدتك...',
    'contact.sendButton': 'إرسال الرسالة',
    'contact.sending': 'جاري الإرسال...',
    'contact.successMessage': 'تم إرسال الرسالة بنجاح! سنرد عليك قريباً.',
    'contact.errorMessage': 'عذراً! حدثت مشكلة أثناء إرسال نموذجك.',
    'apply.heroTitle': 'طلب خطاب دعوة',
    'apply.heroBreadcrumb': 'الرئيسية / الدعوات / طلب دعوة',
    'apply.applyHeading': 'طلب خطاب دعوة',
    'apply.success': 'تم تقديم الطلب بنجاح! سنقوم بمعالجته في غضون 3 أيام عمل.',
    'apply.error': 'عذراً! حدثت مشكلة أثناء تقديم طلبك.',

    // Our Team
    'team.heroTitle': 'فريقنا',
    'team.heroBreadcrumb': 'الرئيسية / حول / فريقنا',
    'team.experiencedProfessionals': 'محترفون ذوو خبرة',
    'team.meetOurExperts': 'تعرف على خبرائنا',
    'team.aboutGlobestar': 'غلوب ستار هي شركة مرموقة وراسخة متخصصة في تقديم وترتيب الدعوات للأفراد الراغبين في زيارة الدول الأوروبية والمملكة المتحدة. فريقنا مكرس للتميز المهني.',
    'team.director': 'مدير غلوب ستار',
    'team.managementOperations': 'الإدارة والعمليات',
    'team.legalConsultant': 'مستشار قانوني',
    'team.visaImmigrationLaw': 'قانون التأشيرات والهجرة',
    'team.seniorConsultant': 'مستشار أول',
    'team.businessImmigrationExpert': 'خبير هجرة الأعمال',
    'team.deepExpertise': 'خبرة عميقة في تسهيل الدعوات لليتوانيا وألبانيا وبيلاروسيا والمملكة المتحدة.',
    'team.combinedExperience': '20 عاماً من الخبرة المشتركة',
    'team.trustOurExpertise': 'ثق في خبرتنا لتسهيل رحلتك وتعزيز فرصك في الحصول على طلب تأشيرة ناجح.',
    'team.reputableCompany': 'شركة مرموقة وراسخة',
    'team.professionallyCrafted': 'خطابات دعوة مصاغة باحترافية',
    'team.alignRequirements': 'تتماشى مع متطلبات طلب التأشيرة المحددة',
    'team.dedicatedSupport': 'فريق دعم مخصص',
    'team.visaSuccessRate': 'معدل نجاح التأشيرات',
    'team.happyClients': 'عملاء سعداء',
    'team.destinations': 'الوجهات',
    'team.clientSupport': 'دعم العملاء',

    // Bank Account
    'bank.heroTitle': 'الحسابات البنكية',
    'bank.heroBreadcrumb': 'الرئيسية / حول / الحسابات البنكية',
    'bank.paymentMethods': 'طرق الدفع',
    'bank.officialAccounts': 'حساباتنا البنكية الرسمية',
    'bank.verifyAccount': 'يرجى استخدام حساباتنا الرسمية فقط لأي مدفوعات. تحقق دائماً من أن اسم الحساب هو غلوب ستار.',
    'bank.copySuccess': 'تم النسخ إلى الحافظة',
    'bank.accountHolder': 'صاحب الحساب',
    'bank.rib': 'رقم الحساب (RIB)',
    'bank.iban': 'رقم الآيبان (IBAN)',
    'bank.swiftCode': 'رمز السويفت (SWIFT)',
    'bank.accountName': 'اسم الحساب',
    'bank.paypalEmail': 'بريد باي بال',
    'bank.status': 'الحالة',
    'bank.verifiedBusiness': 'عمل تجاري موثق',
    'bank.network': 'الشبكة',
    'bank.asset': 'العملة',
    'bank.address': 'العنوان',
    'bank.securePolicy': 'سياسة الدفع الآمن',
    'bank.quickSecure': 'المدفوعات عبر الإنترنت سريعة وآمنة.',
    'bank.immediateConfirmation': 'تأكيد فوري للدفع.',
    'bank.zeroFees': '0% رسوم معاملات للتحويلات البنكية.',
    'bank.whatsappSupport': 'دعم عبر الواتساب للمساعدة في الدفع.',
    'bank.afterPayment': 'بعد إجراء عملية الدفع، يرجى إرسال لقطة شاشة لإيصال المعاملة إلى رقم الواتساب الرسمي لدينا +34 624 13 21 71 أو مراسلتنا عبر البريد الإلكتروني globestarvisa@gmail.com لتسريع المعالجة.',

    // Types of Invitation
    'invitation.heroTitle': 'أنواع الدعوات',
    'invitation.heroBreadcrumb': 'الرئيسية / الدعوات / أنواع الدعوات',
    'invitation.visaDoc': 'وثائق التأشيرة',
    'invitation.typesLetters': 'أنواع خطابات الدعوة',
    'invitation.choosingGlobestar': 'يضمن اختيار غلوب ستار خطاب دعوة مصاغ باحترافية يتماشى مع متطلبات طلب التأشيرة المحددة لكل دولة على حدة.',
    'invitation.visitTitle': 'دعوة تأشيرة زيارة',
    'invitation.visitDef': 'وثيقة مقدمة للأفراد المتقدمين للحصول على تأشيرات زيارة، وتكون بمثابة دعوة رسمية من مضيف أو جهة كفيلة في بلد الوجهة للإقامة معهم.',
    'invitation.businessTitle': 'دعوة تأشيرة عمل',
    'invitation.businessDef': 'خطاب دعوة رسمي من شركة لأغراض تأشيرة العمل، وعادة ما يكون لحضور الاجتماعات أو المؤتمرات أو الارتباطات المهنية.',
    'invitation.familyTitle': 'دعوة تأشيرة عائلية',
    'invitation.familyDef': 'خطاب مكتوب من مضيف أو شركة لأغراض تأشيرة الزيارة العائلية، وهو مطلوب إذا كنت تنوي زيارة أفراد عائلتك في بلد الوجهة.',
    'invitation.touristTitle': 'دعوة تأشيرة سياحية',
    'invitation.touristDef': 'خطاب مكتوب من شركة سياحية مسجلة لأغراض التأشيرة السياحية، يوضح خطة استكشاف وزيارة البلاد.',
    'invitation.privateTitle': 'دعوة خاصة',
    'invitation.privateDef': 'وثيقة مكتوبة من فرد في البلد المضيف لتسهيل الحصول على تأشيرة سياحية أو زيارة خاصة لمقدم الطلب.',
    'invitation.groupTitle': 'دعوة جماعية',
    'invitation.groupDef': 'وثيقة صادرة عن شركة لتسهيل تأشيرات المجموعات السياحية لعدة أفراد يسافرون معاً إلى نفس الوجهة.',
    'invitation.viewPricing': 'عرض الأسعار والتقديم',
    'invitation.whyNeed': 'لماذا تحتاج إلى خطاب دعوة؟',
    'invitation.officersConsider': 'يعتبر ضباط التأشيرات خطاب الدعوة وثيقة داعمة لتقييم جدية الزيارة ونية المتقدم للعودة إلى بلده الأصلي. ثق في خبرتنا لتسهيل رحلتك وتعزيز فرصك في الحصول على طلب تأشيرة ناجح.',
    'country.lithuania': 'ليتوانيا',
    'country.albania': 'ألبانيا',
    'country.uk': 'المملكة المتحدة',
    'country.belarus': 'بيلاروسيا',
    'country.russia': 'روسيا',
    'country.ukraine': 'أوكرانيا',
    'country.spain': 'إسبانيا',
    'country.sweden': 'السويد',
    'country.hungary': 'المجر',
    'country.slovakia': 'سلوفاكيا',
    'country.poland': 'بولندا',

    // Details & Costs
    'costs.heroTitle': 'التفاصيل والتكاليف',
    'costs.heroBreadcrumb': 'الرئيسية / الدعوات / التفاصيل والتكاليف',
    'costs.visaInvitationLetters': 'خطابات دعوة التأشيرة',
    'costs.businessInvitation': 'دعوة عمل',
    'costs.applyNow': 'قدم الآن',
    'costs.note': 'ملاحظة',
    'costs.search': 'بحث',
    'costs.topServices': 'أفضل خدماتنا',
    'costs.anyQuestions': 'هل لديك أي أسئلة؟',
    'costs.callWhatsApp': 'اتصال / واتساب',
    'costs.emailUs': 'راسنا عبر البريد الإلكتروني',
    'costs.invitationLetterHeading': 'خطاب الدعوة',
    'costs.para1': 'خطاب دعوة التأشيرة هو وثيقة مقدمة للأفراد المتقدمين للحصول على تأشيرات سياحية أو زيارة أو عمل أو زيارة عائلية. وهو بمثابة دعوة رسمية من مضيف أو جهة كفيلة في بلد الوجهة. في حين أن خطاب الدعوة نفسه لا يضمن إصدار التأشيرة، إلا أنه يلعب دوراً حاسماً في عملية طلب التأشيرة من خلال توفير معلومات أساسية حول الغرض من الزيارة، ومدة الإقامة، والعلاقة بين مقدم الطلب والمضيف.',
    'costs.para2': 'يعتبر ضباط التأشيرات خطاب الدعوة وثيقة داعمة لتقييم جدية الزيارة ونية مقدم الطلب في العودة إلى بلده الأصلي. على الرغم من أنه ليس ضماناً للموافقة على التأشيرة، إلا أن وجود خطاب دعوة يمكن أن يزيد بشكل كبير من فرص الحصول عليها.',
    'costs.para3': 'في سياق زيارة ليتوانيا وألبانيا وبيلاروسيا والمملكة المتحدة وروسيا وأوكرانيا وإسبانيا والسويد والمجر، يعد الحصول على خطاب دعوة مناسب أمراً ضرورياً. غلوب ستار هي شركة مرموقة وراسخة متخصصة في تقديم وترتيب الدعوات للأفراد الراغبين في زيارة هذه البلدان.',
    'costs.para4': 'بالنسبة لأولئك الذين يخططون لزيارة ليتوانيا، يمكن لـ "خطاب دعوة زائر ليتوانيا" من غلوب ستار أن يساعد في توضيح الغرض من الزيارة، ومدة الإقامة، والعلاقة بين الزائر والمضيف في ليتوانيا.',
    'costs.applyHeading': 'طلب خطاب دعوة',
    'costs.typesHeading': 'أنواع خطابات الدعوة',
    'costs.globestarIsCompany': 'غلوب ستار هي شركة تقدم الأنواع التالية من خطابات الدعوة:',
    'costs.paymentTermsHeading': 'شروط الدفع',
    'costs.paymentPara1': 'نحن نقبل المستندات فقط مع دفع مسبق بنسبة 100%. يمكن الدفع من خلال الحسابات البنكية وبطاقات الائتمان فيزا/ماستركارد. لعرض تفاصيل الحساب البنكي، يرجى زيارة صفحة الخدمات والنقر فوق قسم الحساب البنكي. سيتم إرفاق إيصال الدفع بنموذج الدعوة.',
    'costs.paymentPara2': 'يرجى ملاحظة أن جميع المدفوعات غير قابلة للاسترداد. بمجرد تأكيد الدفع، سنقوم بإصدار خطاب الدعوة في غضون 3 أيام عمل.',
    'costs.paymentPara3': 'سيتم إرسال خطاب الدعوة إلى عنوان بريدك الإلكتروني. إذا كنت بحاجة إلى نسخة ورقية، فسيتم تطبيق رسوم إضافية. تعتمد الرسوم المحددة على بلدك وقد تصل إلى 65 دولاراً.',
    'costs.howToGetHeading': 'كيف تحصل على خطاب دعوة؟',
    'costs.step1Title': 'املأ نموذج الدعوة',
    'costs.step1Text': 'يرجى التأكد من ملء نموذج الدعوة عبر الإنترنت بالهجاء الصحيح وفقاً للمعلومات الواردة في جواز سفرك',
    'costs.step2Title': 'أرفق جواز السفر وتابع الدفع',
    'costs.step2Text': "بعد ملء النموذج، يرجى إرفاق نسخة ممسوحة ضوئياً من جواز سفرك، ثم النقر فوق زر 'إرسال' ومتابعة الدفع.",
    'costs.step3Title': 'استعد لاستلام دعوتك',
    'costs.step3Text': 'بعد استلام طلبك ونسخة جواز السفر وتأكيد الدفع، سنرسل خطاب الدعوة إلى بريدك الإلكتروني في غضون 3 أيام عمل.',
    'costs.faqHeading': 'الأسئلة الشائعة',
    'costs.faq1Q': 'كم يستغرق معالجة خطاب دعوة التأشيرة؟',
    'costs.faq1A': 'عادةً، نقوم بمعالجة خطابات دعوة التأشيرة في غضون ثلاثة أيام عمل ونرسلها عبر البريد الإلكتروني. ومع ذلك، قد يستغرق الشحن من 3 إلى 10 أيام تقريباً، اعتماداً على بلد الوجهة.',
    'costs.faq2Q': 'هل تقومون أيضاً بمعالجة طلبات التأشيرة للمتقدمين؟',
    'costs.faq2A': 'نحن نقدم وثائق دعم التأشيرة (الدعوات) ولكن يجب تقديم الطلب النهائي من قبل مقدم الطلب في السفارة أو مركز التأشيرات.',
    'costs.faq3Q': 'كيف يمكننا التحقق من أصالة وقانونية الدعوة؟',
    'costs.faq3A': 'جميع دعواتنا صادرة عن شركات مسجلة قانونياً ويمكن التحقق منها من خلال بوابات الهجرة الحكومية المعنية عند الاقتضاء.',
    'costs.noteMediation': 'خطاب الوساطة المعتمد من الهجرة يكلف 750 يورو.',
    'costs.notePerPerson': 'تكلفة خطاب الدعوة العائلي هي للشخص الواحد.',
    'costs.notePolice': 'خطاب دعوة العمل معتمد من الشرطة/القاضي',
    'costs.noteTouristType': 'سيكون خطاب الدعوة العائلي من النوع السياحي.',
    'country.estonia': 'إستونيا',
    'country.serbia': 'صربيا',
    'country.kosovo': 'كوسوفو',
    'country.cyprus': 'قبرص',
    'country.luxembourg': 'لوكسمبورغ',
    'country.netherlands': 'هولندا',
    'country.germany': 'ألمانيا',
    'country.czech': 'جمهورية التشيك',
    'country.denmark': 'الدنمارك',
    'country.finland': 'فنلندا',
    'country.france': 'فرنسا',
    'country.iceland': 'آيسلندا',
    'country.norway': 'النرويج',
    'country.portugal': 'البرتغال',
    'country.ireland': 'آيرلندا',
    'invitation.visit': 'دعوة زيارة',
    'invitation.business': 'دعوة عمل',
    'invitation.family': 'دعوة عائلية',
    'invitation.tourist': 'دعوة سياحية',
    'invitation.perPerson': 'للشخص الواحد',
    'invitation.policeApproved': 'دعوة معتمدة من الشرطة',

    // Available Visas
    'visas.heroTitle': 'التأشيرات المتاحة',
    'visas.heroBreadcrumb': 'الرئيسية / التأشيرات / نظرة عامة',
    'visas.servicesCategories': 'فئات الخدمات',
    'visas.exploreServices': 'استكشف خدمات التأشيرات لدينا',
    'visas.exploreDesc': 'اكتشف مجموعة واسعة من خدمات التأشيرات والهجرة المصممة خصيصاً لتلبية احتياجاتك. من تصاريح العمل في أوروبا إلى القبود الدراسي في المملكة المتحدة.',
    'visas.visitingDesc': 'تصاريح سفر للسياحة والترفيه. تتضمن خيارات التأشيرة الإلكترونية لدول مثل ألبانيا ومولدوفا وجورجيا.',
    'visas.studyingDesc': 'تصاريح تعليمية لجامعات المملكة المتحدة وأيرلندا وألمانيا. تتضمن دعماً لبرامج اللغة.',
    'visas.businessDesc': 'خدمات مخصصة لرجال الأعمال الراغبين في العيش والعمل في ليتوانيا وإستونيا والمملكة المتحدة من خلال تأسيس الأعمال.',
    'visas.companyDesc': 'تأسيس شركات سريع وسهل في دول الاتحاد الأوروبي. مساعدة قانونية كاملة لتأسيس عملك التجاري.',
    'visas.invitationDesc': 'خطابات دعوة رسمية من الشركة مطلوبة لطلبات التأشيرة. فئات العمل والعائلة والزيارة.',
    'visas.viewDetails': 'عرض التفاصيل',
    'visas.readyToStart': 'هل أنت مستعد لبدء رحلة طلبك؟',
    'visas.expertsAvailable': 'خبراؤنا متاحون على مدار الساعة طوال أيام الأسبوع على الواتساب لتقديم تقييم مجاني لأهليتك.',

    // Visiting Visa
    'visiting.heroTitle': 'تأشيرات الزيارة والتأشيرات الإلكترونية',
    'visiting.heroBreadcrumb': 'الرئيسية / التأشيرات / تأشيرات الزيارة',
    'visiting.servicesTitle': 'خدمات التأشيرة الإلكترونية',
    'visiting.applyHeading': 'طلب تأشيرة إلكترونية',
    'visiting.para1': 'تسمح تأشيرات السفر لحاملها بدخول بلد أجنبي لأغراض السياحة والترفيه فقط، وعادة ما تكون لها مدة إقامة محددة. ومع ذلك، من المهم ملاحظة أن هذه التأشيرات بشكل عام لا تمنح حاملها الحق في العمل أو المشاركة في أي أنشطة تجارية أثناء وجوده في البلد المضيف.',
    'visiting.para2': 'تمنح السفارة/ الهجرة ثلاثة أنواع من التأشيرات للمتقدمين، 1. eTA (تأشيرة إلكترونية)، 2. تأشيرة ختم و 3. تأشيرة ملصق. نحن نقدم تأشيرات eTA للعديد من البلدان التي تقدمها ولكن هذه لمواطني دول محددة.',
    'visiting.howToGetHeader': 'كيف تحصل على تأشيرة؟',
    'visiting.step1Title': 'املأ نموذج الطلب',
    'visiting.step1Text': 'يرجى التأكد من إكمال نموذج الطلب عبر الإنترنت بالهجاء الدقيق حسب المعلومات الواردة في جواز سفرك.',
    'visiting.step2Title': 'أرفق جواز السفر وادفع الرسوم',
    'visiting.step2Text': "بعد إكمال النموذج، يرجى تحميل نسخة ممسوحة ضوئياً من جواز سفرك والمتابعة للدفع بالنقر فوق 'دفع'. أخيراً، انقر فوق زر 'إرسال'.",
    'visiting.step3Title': 'قدم طلبك',
    'visiting.step3Text': 'بعد استلام طلبك ونسخة جواز السفر وتأكيد الدفع، سنقوم بمعالجة تأشيرتك الإلكترونية وإخطارك عبر البريد الإلكتروني.',
    'visiting.typesHeading': 'أنواع تأشيرات الزيارة',
    'visiting.generalTitle': 'تأشيرة زيارة عامة',
    'visiting.generalText': 'هذا النوع من تأشيرات الزيارة صالح عادةً لمدة محدودة، تتراوح من بضعة أيام إلى بضعة أشهر، اعتماداً على لوائح الدولة. عند انتهاء الصلاحية، قد تحتاج إما إلى تجديدها أو العودة إلى بلدك الأصلي.',
    'visiting.familyTitle': 'تأشيرة زيارة عائلية',
    'visiting.familyText': 'تسمح تأشيرات الزيارة العائلية لك بالإقامة في بلد أجنبي مع عائلتك. اعتماداً على سياسات الدولة المحددة، قد تكون مؤهلاً للتقدم بطلب التجديد بعد فترة معينة من الإقامة.',
    'visiting.businessTitle': 'تأشيرة زيارة عمل',
    'visiting.businessText': 'تمكنك تأشيرات زيارة العمل من العيش في بلد أجنبي وتأسيس عملك هناك. بعد ممارسة الأنشطة التجارية لفترة محددة، قد تكون مؤهلاً للتقدم بطلب للحصول على وضع الإقامة المؤقتة.',
    'visiting.docReqHeading': 'متطلبات الوثائق',
    'visiting.reqPassport': 'مسح ضوئي لجميع صفحات جواز السفر الحالي.',
    'visiting.reqID': 'مسح ضوئي لبطاقة الهوية/الإقامة.',
    'visiting.reqPhoto': 'صورة رقمية بخلفية بيضاء.',
    'visiting.reqPolice': 'شهادة حسن سيرة وسلوك (إذا لزم الأمر)',

    // Studying Visa
    'studying.heroTitle': 'تأشيرات الدراسة والقبولات',
    'studying.heroBreadcrumb': 'الرئيسية / التأشيرات / تأشيرات الدراسة',
    'studying.servicesTitle': 'قبول الطلاب',
    'studying.opportunitiesHeading': 'فرص الدراسة في الخارج',
    'studying.intro': 'تقدم غلوب ستار خدمات القبول للدراسة في المملكة المتحدة وأيرلندا. نحن نتعاون مع مجموعة واسعة من الجامعات التي تقدم برامج تشمل ESL و ESOL والتأسيسية والبكالوريوس والدراسات العليا في مختلف المجالات.',
    'studying.ukTitle': 'المملكة المتحدة',
    'studying.ukDesc': 'ادرس في المملكة المتحدة مع أفضل الجامعات.',
    'studying.irelandTitle': 'أيرلندا',
    'studying.irelandDesc': 'تابع شهادتك في المدن الكبرى في أيرلندا.',
    'studying.germanyTitle': 'ألمانيا',
    'studying.germanyDesc': 'استكشف التميز التعليمي في ألمانيا.',
    'studying.languageProgHeading': 'طلب لبرامج اللغة',
    'studying.languageIntro': 'للتقدم لبرامج اللغة، لا داعي لإجراء امتحان الآيلتس (IELTS). لا توجد قيود على العمر، ولا تعتبر الفجوات الدراسية مشكلة. يمكن دفع الرسوم الدراسية بعد الحصول على التأشيرة.',
    'studying.howLongHeading': 'كم من الوقت يستغرق؟',
    'studying.studyVisaProcess': 'تأشيرة الدراسة: تُعالج عادةً في غضون شهر إلى شهرين، اعتماداً على الدولة والسفارة.',
    'studying.admissionProcess': 'القبول: يُعالج في غضون أسبوعين إلى أربعة أسابيع.',
    'studying.docReqHeading': 'متطلبات الوثائق',
    'studying.reqEdu': 'جميع الوثائق التعليمية (المتوفرة).',
    'studying.reqResume': 'سيرة ذاتية مع تفاصيل التعليم والعمل.',
    'studying.spain': 'إسبانيا',
    'studying.italy': 'إيطاليا',
    'studying.poland': 'بولندا',
    'studying.france': 'فرنسا',
    'studying.spanish': 'اللغة الإسبانية',
    'studying.italian': 'اللغة الإيطالية',
    'studying.polish': 'اللغة البولندية',
    'studying.french': 'اللغة الفرنسية',
    'studying.applyNow': 'قدم الآن',

    // Company Registration
    'company.heroTitle': 'تسجيل الشركات',
    'company.heroBreadcrumb': 'الرئيسية / الخدمات / تسجيل الشركات',
    'company.supportHeading': 'الدول التي نقدم الدعم فيها',
    'company.servicesHeading': 'خدمات تسجيل الشركات',
    'company.intro': 'نسهل ونسرع عملية تأسيس عملك التجاري. نحن نقدم مساعدة قانونية كاملة في تسجيل شركتك.',
    'company.regLabel': 'تسجيل شركة',
    'company.basicPackage': 'الباقة الأساسية',
    'company.needDetails': 'هل تحتاج إلى مزيد من التفاصيل؟',
    'company.contactForDetails': 'لمزيد من التفاصيل اتصل بنا عبر البريد الإلكتروني والواتساب',
    'company.getInTouch': 'تواصل معنا',
    'company.disclaimer': 'غلوب ستار هي شركة ليتوانية معتمدة مسجلة في "مركز سجلات الشركات الحكومية". رقم تسجيلنا هو 306016085.',

    // Business Immigration
    'immigration.heroTitle': 'الهجرة للأعمال',
    'immigration.heroBreadcrumb': 'الرئيسية / الهجرة / الهجرة للأعمال',
    'immigration.entrepreneurServices': 'خدمات ريادة الأعمال',
    'immigration.availableCountries': 'الهجرة للأعمال متاحة في الدول التالية',
    'immigration.startingAt': 'تبدأ من',
    'immigration.readMore': 'اقرأ المزيد',
    'immigration.trustedAssistance': 'مساعدة مهنية موثوقة',
    'immigration.lithuaniaDesc': 'تتعامل شركتنا حصرياً مع الهجرة للأعمال إلى ليتوانيا ولديها خيار موثوق للحصول على تأشيرة عمل متعددة الدخول لمدة عام.',
    'immigration.estoniaDesc': 'تتعامل شركتنا حصرياً مع الهجرة للأعمال إلى إستونيا ولديها خيار موثوق للحصول على تأشيرة عمل متعددة الدخول لمدة عام.',
    'immigration.albaniaDesc': 'تقدم غلوب ستار مجموعة كاملة من خدمات الهجرة للأفراد الأجانب ورواد الأعمال الذين يرغبون في زيارة وألبانيا والعيش والعمل فيها.',
    'immigration.belarusDesc': 'تصريح الإقامة المؤقتة في بيلاروسيا هو وثيقة تصدر لغير المواطنين الذين يرغبون في الحصول على فرصة للهجرة والعيش والعمل في بيلاروسيا.',
    'immigration.ukDesc': 'كل ما تحتاجه لتسجيل وإدارة شركة في المملكة المتحدة. نحن نقدم مساعدة قانونية كاملة في تسجيل شركتك في المملكة المتحدة.',
    'immigration.irelandDesc': 'كل ما تحتاجه لتسجيل وإدارة شركة في أيرلندا. نحن نقدم مساعدة قانونية كاملة في تسجيل شركتك في أيرلندا.',
    'immigration.visaProcessing': 'معالجة التأشيرات',
    'immigration.regIn': 'تسجيل في',
    'immigration.regLabel': 'تسجيل الشركات',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return (translations[language] as any)[key] || (translations['en'] as any)[key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
